apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wuxamfn27-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:703966cfe7f03cc23ac2030e234f8f813b5bbc1d@sha256:05f108c8e7a1dcdc23d06e177a0dfdbf8292ddc63a7473e25b350651c1b809c9
          name: container-image
